# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: dnr00@naver.com
author_name: uksang 29
contract_name: hello_algo
deployment_language: python
preset_name: starter
project_name: Hello_Algo

